name: flutter_architecture
description: Clean architecture project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  fa_business:
    path: ./packages/fa_business
  fa_models:
    path: ./packages/fa_models
  get_it: ^7.2.0
  injectable: ^2.1.0
  json_annotation: ^4.7.0
  provider: ^6.0.5

dev_dependencies:
  build_runner: ^2.1.15
  fa_analyzer:
    path: ./packages/fa_analyzer
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  injectable_generator: ^2.1.3
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
